[project]
dependencies = ["pandas>=2.3.3,<3", "tensorboard>=2.20.0,<3", "torchvision>=0.24.1,<0.25", "matplotlib>=3.10.8,<4"]
name = "torchleet"
requires-python = ">= 3.13"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]

[tool.pixi.tasks]

[tool.pixi.dependencies]
#pytorch = ">=2.9.1,<3"
marimo = ">=0.18.4,<0.19"
torchvision = ">=0.24.1,<0.25"
python-lsp-ruff = ">=2.3.0,<3"
python-lsp-server = ">=1.14.0,<2"

[tool.pixi.feature.gpu.system-requirements]
cuda = "12.0"

[tool.pixi.feature.gpu.dependencies]
cuda-version = "12.*"
pytorch-gpu = ">=2.9.1,<3"

[tool.pixi.feature.cpu.dependencies]
pytorch-cpu = ">=2.9.1,<3"

[tool.pixi.environments]
cpu = ["cpu"]
default = ["gpu"]

# Language server configuration
[tool.marimo.language_servers.pylsp]
enabled = true               # Enable/disable the Python language server
enable_mypy = true           # Type checking with mypy (enabled by default, if installed)
enable_ruff = true           # Linting with ruff (enabled by default, if installed)
enable_flake8 = false        # Linting with flake8
enable_pydocstyle = false    # Check docstring style
enable_pylint = false        # Linting with pylint
enable_pyflakes = false      # Syntax checking with pyflakes

# Diagnostics configuration
[tool.marimo.diagnostics]
enabled = true               # Show diagnostics in the editor

